# IOP configuration used to install the demo profile without gateways.
apiVersion: install.istio.io/v1
kind: IstioOperator
spec:
  profile: demo
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
    egressGateways:
      - name: istio-egressgateway
        enabled: false
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100