server:
  port: 5001
  servlet:
    context-path: /v1/customers

spring:
  application:
    name: customers
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.ecommerce.svc.cluster.local:8080/realms/ecommerce/protocol/openid-connect/certs